### ISSUE TITLE
Extra Fee missing from Contribution Total

### ISSUE THREAD

**Issue by mwestergaard** [fuzionnz/nz.co.fuzion.extrafee#18]
I just noticed that the extra fee is no longer saved in Contribution Total. The confirmation page shows it:
![image](https://user-images.githubusercontent.com/38840269/129836227-9dd81ccf-e3a1-42ca-9c16-daa8f69cb5a8.png)
but it isn't in the receipt or the donation record:
![image](https://user-images.githubusercontent.com/38840269/129837381-5226fa44-2847-4ad1-8a6b-4c50016ff3a3.png)
Here's an earlier sample record:
![image](https://user-images.githubusercontent.com/38840269/129837339-0b9b6810-b2a2-4d75-b4de-0d6b0bf591ff.png)
I am at CiviCRM 5.40.2. I'm using PayPal Checkout with Ominpay extension. I also tested with PayPal Standard.

**Comment by mwestergaard** [comment]
Just upgraded to CiviCRM 5.41.0 on Wordpress 5.8 and tried a test transaction. This issue seems to be corrected. I will do some additional testing.

**Comment by mwestergaard** [comment]
All good. I'll close.

**Comment by jmcclelland** [comment]
Thanks for this report, it was really helpful for me.

This problem currently affects CIviCRM Core LTS version 5.39. 

Thanks to your report of the versions involved, I was able to trace the bug to this PR: https://github.com/civicrm/civicrm-core/pull/20357

And, trace the fix to this PR: https://github.com/civicrm/civicrm-core/pull/21212

On the fix, the specific and minimal commit that you need to fix the problem is:
https://github.com/civicrm/civicrm-core/pull/21212/commits/8da4799e81329c6eab458975d6da9e0a7f18933a (you can cherry pick that into 5.39 to resolve this issue).
